holidayshare/holidayshare/urls.py
#holidayshare URl
from django.conf.urls import url,include
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^$',views.MainPage.as_view(),name='index'),
    url(r'^members/',include('members.urls',namespace='members')),
    url(r'^members/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name ='test'),
    url(r'^thanks/$',views.Thanks.as_view(),name= 'thanks'),
    url(r'^admin/', admin.site.urls),
    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^api/posts/',include('posts.api.urls', namespace='posts-api'))
]

holidayshare/posts/api/urls.py
from django.conf.urls import url
from . import views


urlpatterns =[
    url(r'^$',views.PostListApi.as_view(),name='postlist'),
    url(r'^create/$',views.PostCreateApi.as_view(), name ='create'),
    url(r'^(?P<slug>[\w-]+)/$',views.PostDetailApi.as_view(),name='single'),


]

holidayshare/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'


urlpatterns=[
    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'new/$',views.CreatePost.as_view(),name='create'),
    url(r'userpost/(?P<username>[-\w]+)',views.UserPost.as_view(),name='for_user'),
    url(r'(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    url(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
]

holidayshare/posts/models.py
#Posts Model
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
import misaka
from groups.models import Group
from django.contrib.auth import get_user_model
User = get_user_model()
from django.utils.text import slugify


class Post(models.Model):
    user = models.ForeignKey(User,related_name='posts', null=True)
    created_date = models.DateTimeField(auto_now =True, null=True)
    message = models.TextField(max_length=500)
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group,related_name='posts',null=True,blank=True)
    slug = models.SlugField(allow_unicode=True, null=True, unique = True)


    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        self.slug = slugify(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'slug': self.slug})


    def __str__(self):
        return self.message

    class Meta:
        ordering =['created_date']
        unique_together = ['user','message']

holidayshare/posts/forms.py
from django import forms

from posts import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = (models.Group.objects.filter(pk__in=user.groups.values_list("group__pk")))

holidayshare/posts/api/views.py
from posts.models import Post
from .serializers import PostListSerializer, PostDetailSerializer, PostCreateSerializer
from rest_framework import generics



class PostListApi(generics.ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostListSerializer


class PostDetailApi(generics.RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'


class PostCreateApi(generics.CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateSerializer

holidayshare/posts/views.py
# from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.http import Http404
from braces.views import SelectRelatedMixin
from . import models
from . import forms
from django.contrib.auth import get_user_model
User = get_user_model()

class PostList(SelectRelatedMixin, generic.ListView):

    model = models.Post
    select_related = ('user','group')

class UserPost(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post.user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))

        except User.DoestNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields = ('message','group')
    model = models.Post

    def form_valid(self,form):
        self.object = form.save(commit = False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self,*args,**kwargs):
        message.success(self.request,'You Have Deleted The Post')
        return super().delete(*args, **kwargs)

holidayshare/posts/templates/posts/_post.html
<div class="post media">
	<h3>{{ post.message_html|safe }}</h3>
	<div class="media-body">
		<strong>{{ post.user.username }}</strong>
		<h5 class="media-heading">
			<span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
			<time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
			{% if post.group %}
			<span class="group-name">in <a href="#">{{ post.group.name }}</a></span>
			{% endif %}
		</h5>




		<div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

holidayshare/posts/templates/posts/post_base.html
{% extends "base.html" %}
{% block content %}
<div class="post-page">
  <div class="container">
    <div class="row">
      {% block prepost %}{% endblock %}
      {% block post_content %}{% endblock %}
      {% block post_post %}{% endblock %}

    </div>
  </div>
</div>

{% endblock %}

holidayshare/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}
{% block post_content %}
<div class="container">
  <h3>Are You Sure you want to delete your memory?</h3>
    <div class="posts">
      {% include "posts/_post.html" with post=object hide_delete=True %}

    </div>
    <form method="POST">
       {% csrf_token %}
       <input type="submit" class="btn btn-danger btn-large" value="Delete?">
       <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class='btn btn-primary btn-large'>Cancel</a>    
    </form>
</div>


{% endblock %}

</div>

holidayshare/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}
{% block post_content %}
<div class="col-md-8">
{% include "posts/_post.html" %}  
</div>

{% endblock %}

holidayshare/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap4 %}
{% block post_content %}
<h4>Create New Memory</h4>
<form id="postForm" action=".html{% url 'posts:create' %}" method="POST">
{% csrf_token %}
{% bootstrap_form form%}
<input type="submit" class="btn btn-primary btn-large" value="share">
</form>

{% endblock %}

holidayshare/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% block prepost %}
<div class="col-md-4">
  {% if user.is_authenticated %}
  <div class="card card-with-shadow">
    <div class="content">
      <h5 class='title'> List of Your Group</h5>
      <ul clas='list-unstyled'>
        {% for member_group in get_user_groups %}
        <li class='group li-with-bullet'>
          <a href="{% url 'groups:single' slug=member_group.group.slug %}"></a>
        </li>

        {% endfor %}

      </ul>
    </div>
  </div>

    {% endif %}
    <div class="card card-with-shadow">
      <div class="content">
        <h2 class='title'> All groups</h2>
        <ul class='list-unstyled'>
          {% for other_group in get_other_groups %}
          <li class='group li-with-bullet'>
            <a href="{% url 'groups:single' slug=other_group.slug %}"></a>
          </li>

          {% endfor %}

        </ul>
      </div>
    </div>
</div>

{% endblock %}
{% block post_content %}
<div class="col-md-8">

{% for post in post_list %}
  {% include "posts/_post.html" %}
  

{% endfor %}
  </div>
{% endblock %}

holidayshare/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}
{% block prepost %}
<div class="col-md-4">
  <h2>@{{post_user.username}}</h2>
</div>
  {% block post_content %}
  <div class="col-md-8">
      {% for post in post_list %}
      {% include "posts/_post.html" %}
      {% endfor %}
  </div>

  {% endblock %}
{% endblock %}