holidayshare/holidayshare/urls.py
#holidayshare URl
from django.conf.urls import url,include
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^$',views.MainPage.as_view(),name='index'),
    url(r'^members/',include('members.urls',namespace='members')),
    url(r'^members/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name ='test'),
    url(r'^thanks/$',views.Thanks.as_view(),name= 'thanks'),
    url(r'^admin/', admin.site.urls),
    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^api/posts/',include('posts.api.urls', namespace='posts-api'))
]

holidayshare/members/urls.py
#members URl
from . import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views

app_name = 'members'

urlpatterns =[
    url(r'login/$',auth_views.LoginView.as_view(template_name='members/login.html'), name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(), name='logout'),
    url(r"signup/$", views.Register.as_view(), name="register"),
]

holidayshare/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'


urlpatterns=[
    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'new/$',views.CreatePost.as_view(),name='create'),
    url(r'userpost/(?P<username>[-\w]+)',views.UserPost.as_view(),name='for_user'),
    url(r'(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    url(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
]

holidayshare/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Holiday Memories</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {# <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">#}

    <link rel="stylesheet" href="{% static 'holidayshare/css/master.css' %}">
  </head>
  <body>
    <nav class="navbar  mynav" role="navigation" id="navbar">
      <div class="container">

        <a class="navbar-brand mynav" href="{% url 'index' %}">Holiday Share</a>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                  <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Posts</a></li>
                  <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                  <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                  <li><a href="{% url 'members:logout' %}" class="btn btn-simple">Log out</a></li>
            {% else %}
                  <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></li>
                  <li><a href="{% url 'members:login' %}" class="btn btn-simple">Log in</a></li>
                  <li><a href="{% url 'members:register' %}" class="btn btn-simple">Sign up</a></li>
            {% endif %}
          </ul>

      </div>
    </nav>


<div class="container mycontent">

{% block content %}
{% endblock %}
</div>

  </body>
</html>

holidayshare/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>WELCOME TO SOCIAL HOLIDAY PAGE</h1>
<h3>Please login or register to share your holiday memories.</h3>


{% endblock %}

holidayshare/templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>Welcome To Your Profile!</h1>
  

{% endblock %}

holidayshare/templates/thanks.html
{% extends "base.html" %}
{% block content %}
  <h1>You have successfully logged Out, Thanks for visiting! </h1>
{% endblock %}