holidayshare/groups/templates/groups/urls.py
#Groups url
from django.conf.urls import url
from . import views

app_name = 'groups'

urlpatterns=[
    url(r'^$',views.ListGroups.as_view(),name='all'),
    url(r'^create/$',views.BuildGroup.as_view(),name='create'),
    url(r'posts/in/(?P<slug>[-/w]+)/$',views.SingleGroup.as_view(),name='single'),

]

holidayshare/groups/urls.py
from django.conf.urls import url
from . import views

app_name = 'groups'

urlpatterns=[
    url(r'^$',views.ListGroups.as_view(),name='all'),
    url(r'^new/$',views.BuildGroup.as_view(),name='create'),
    url(r'posts/in/(?P<slug>[-\w]+)/$',views.SingleGroup.as_view(),name='single'),
    url(r'join/(?P<slug>[-\w]+)/$',views.JoinGroup.as_view(),name='join'),
    url(r'leave/(?P<slug>[-\w]+)/$',views.LeaveGroup.as_view(),name='leave'),
]

holidayshare/holidayshare/urls.py
#holidayshare URl
from django.conf.urls import url,include
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^$',views.MainPage.as_view(),name='index'),
    url(r'^members/',include('members.urls',namespace='members')),
    url(r'^members/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name ='test'),
    url(r'^thanks/$',views.Thanks.as_view(),name= 'thanks'),
    url(r'^admin/', admin.site.urls),
    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^api/posts/',include('posts.api.urls', namespace='posts-api'))
]

holidayshare/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'


urlpatterns=[
    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'new/$',views.CreatePost.as_view(),name='create'),
    url(r'userpost/(?P<username>[-\w]+)',views.UserPost.as_view(),name='for_user'),
    url(r'(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    url(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
]

holidayshare/groups/models.py
#Members Models
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.text import slugify
import misaka
from django.contrib.auth import get_user_model
User = get_user_model()
from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=40,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    country = models.CharField(max_length=40,unique = True)
    description = models.TextField(blank=True)
    description_html = models.TextField(editable=False, blank=True)
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)
    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Meta:
        ordering =['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='membership')
    user = models.ForeignKey(User,related_name='user_groups')
    def __st__(self):
        return self.user.username


    class Meta:
        unique_together = ('group','user')

holidayshare/groups/views.py
#members Views
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib import messages
from . models import Group,GroupMember
from . import models

class BuildGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name', 'description')
    model = Group


class SingleGroup(generic.DetailView):
    model = Group


class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request, *args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))
        try:
            GroupMember.objects.create(user=self.request.user, group = group)
        except:
            messages.warning(self.request,('Ops! You are already a member'))
        else:
            messages.success(self.request,('You Have Joined!! '))
        return super().get(request,*args, **kwargs)



class LeaveGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args, **kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request, *args, **kwargs):
        try:
            membership = models.GroupMember.objects.filter(user=self.request.user,group__slug=self.kwargs.get('slug')).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,'You are not a member')
        else:
            membership.delete()
            messages.success(self.request,'You have left the Group')
        return super().get(request,*args,**kwargs)

holidayshare/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    {% block pregroup %}
    {% endblock %}
    {% block group_content %}
    {% endblock %}
    {% block postgroup %}
    {% endblock %}
  </div>
</div>

{% endblock %}

holidayshare/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
<h1>{{group.name}}</h1>
  <h2>Number of Members: {{ group.members.count }}</h2>
    <div class="content">
    {% if user in group.members.all %}
    <a href="{% url 'groups:leave' slug=group.slug %}" class='btn btn-lg btn-fill btn-warning'>
      <span class='glyphicon glyphicon-remove-circle'></span>Leave Group</a>
      {% else %}
      <a href="{% url 'groups:join' slug=group.slug %}" class='btn btn-lg btn-fill btn-success'>
        <span class='glyphicon glyphicon-ok-circle'></span>Join Group</a>
    {% endif %}

    </div>
{% endblock %}
{% block group_content %}
<div class="col-md-8">
  {% if group.posts.count == 0 %}
  <h2>This is a new Group! Start Sharing you Memories</h2>
  {% else %}
  {% for post in group.posts.all %}
  {% include "posts/_post.html" %}

  {% endfor %}

  {% endif %}

</div>

{% endblock %}

holidayshare/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap4 %}
{% block group_content %}
<h3>Create a new Group Here!</h3>
<form action="{% url 'groups:create' %}" method="POST" id='groupForming'>
  {% csrf_token %}
  {% bootstrap_form form %}
<input type="submit" name="btn btn-primary btn-large" value="Create Group">
</form>

{% endblock %}

holidayshare/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>Welcome! Please choose your Group
			<a href="{% url 'posts:for_user' username=user.username %}">@{{ user.username }}</a>
		</h2>

    {% endif %}
			<h2>Group List</h2>

			<p>Welcome to the Groups list! please select a Grouo</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Group!</a>
	{% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
		  <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}
					</div>
					<div class="col-md-4">
						<span class="badge">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}